"""v0.1.5

迁移 ID: 6db03f05b9e6
父迁移: fdd1eb13dd74
创建时间: 2026-03-15 19:59:43.723569

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6db03f05b9e6"
down_revision: str | Sequence[str] | None = "fdd1eb13dd74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
